from enum import Enum

class EnvironmentKeys(Enum):
    CONNECTION_STRING = "CONNECTION_STRING"
    OS = "OS"
    DB_USER = "DB_USER"
    DB_PASS = "DB_PASS"
    DB_HOST = "DB_HOST"
    DB_PORT = "DB_PORT"
    DB_NAME = "DB_NAME"
    SECRET_KEY = "SECRET_KEY"
    TWITTER_API_KEY = "TWITTER_API_KEY"
    TWITTER_API_SECRET = "TWITTER_API_SECRET"
    TWITTER_CLIENT_ID = "TWITTER_CLIENT_ID"
    TWITTER_CLIENT_SECRET = "TWITTER_CLIENT_SECRET"
    FRONTEND_URL = "FRONTEND_URL"


class TestEnvironmentKeys(Enum):
    CONNECTION_STRING = "CONNECTION_STRING"
    SECRET_KEY = "SECRET_KEY"