version: '3.8'

services:
  solana_llm:
    build:
      context: ./backend/llm/solana
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080 

  frontend:
    build:
      context: ./frontend_app
      dockerfile: Dockerfile
    ports:
      - "9123:9123"
    environment:
      - NODE_ENV=production 