version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend_app/.env
    restart: always 